### ISSUE TITLE
S3Auth doesn't work in Munki

### ISSUE THREAD

**Issue by ghost** [waderobson/s3-auth#14]
Hello,

First of all thanks for your work on s3-auth, i have a private repo on S3 bucket and i have follow your process to make it work with munki, but it's not working, below you will find the error i'm getting with munki:

XeroxBrain:munki admin$ sudo /usr/local/munki/managedsoftwareupdate
Managed Software Update Tool
Copyright 2010-2020 The Munki Project
https://github.com/munki/munki

Starting...
Checking for available updates...
    Retrieving list of software for this machine...
ERROR: Could not retrieve manifest Packages from the server: HTTP result 403: forbidden
ERROR: Could not retrieve managed install primary manifest.
Finishing...

My bucket URL is working as i have try it by making the bucket repo public.
My Access key ID and Secret access key are also good.
I have copy middleware_s3.py in /usr/local/munki/ folder

I have also set 
sudo defaults write /Library/Preferences/ManagedInstalls AccessKey 'xxxxxxx'
sudo defaults write /Library/Preferences/ManagedInstalls 'xxxxxx'
sudo defaults write /Library/Preferences/ManagedInstalls Region 'eu-west-1’
sudo defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL  ‘xxxxxxxxx'

Thanks for you help.

**Comment by derekjbernard** [comment]
sudo defaults write /Library/Preferences/ManagedInstalls 'xxxxxx'

should be:
sudo defaults write /Library/Preferences/ManagedInstalls SecretKey  'xxxxxx'

**Comment by ghost** [comment]
Hello @derekjbernard , 
Sorry for the late reply.
The issue is solved, it was because of SoftwareRepoURL, the url was not the right one, i was using this url with the bad region:
https://bucketname.s3-eu-west-1.amazonaws.com/repo
region global

This url and region fixed the issue:
https://bucketname.s3.amazonaws.com/repo
Region: eu-west-1'

Thanks again.
Have a nice week-end !
