### ISSUE TITLE
Authentication not passing through

### ISSUE THREAD

**Issue by jaredsiegel** [waderobson/s3-auth#7]
The error I was receiving looked like this:

> iMac:~ admin$ sudo managedsoftwareupdate -v
> Managed Software Update Tool
> Copyright 2010-2017 The Munki Project
> https://github.com/munki/munki
> 
> Starting...
> Checking for available updates...
>     Getting manifest ms/ms...
> ERROR: Unexpected error in updatecheck:
> Traceback (most recent call last):
>   File "/usr/local/munki/managedsoftwareupdate", line 1055, in <module>
>     main()
>   File "/usr/local/munki/managedsoftwareupdate", line 781, in main
>     client_id=options.id.decode('UTF-8'))
>   File "/usr/local/munki/munkilib/updatecheck/core.py", line 76, in check
>     mainmanifestpath = manifestutils.get_primary_manifest(client_id)
>   File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 156, in get_primary_manifest
>     manifest = get_manifest(clientidentifier)
>   File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 114, in get_manifest
>     manifesturl, manifestpath, message=message)
>   File "/usr/local/munki/munkilib/fetch.py", line 425, in munki_resource
>     verify=verify)
>   File "/usr/local/munki/munkilib/fetch.py", line 378, in getResourceIfChangedAtomically
>     message=message, resume=resume, follow_redirects=follow_redirects)
>   File "/usr/local/munki/munkilib/fetch.py", line 510, in getHTTPfileIfChangedAtomically
>     follow_redirects=follow_redirects)
>   File "/usr/local/munki/munkilib/fetch.py", line 236, in get_url
>     options = middleware.process_request_options(options)
>   File "/usr/local/munki/middleware_s3.py", line 114, in process_request_options
>     headers = s3_auth_headers(options['url'])
>   File "/usr/local/munki/middleware_s3.py", line 94, in s3_auth_headers
>     signing_key = get_signature_key(SECRET_KEY, datestamp, REGION, SERVICE)
>   File "/usr/local/munki/middleware_s3.py", line 45, in get_signature_key
>     kdate = sign(('AWS4' + key).encode('utf-8'), datestamp)
> TypeError: cannot concatenate 'str' and 'NoneType' objects
> 

It turns out the latest version of s3-auth changes the location where it reads the preferences. The old location for the settings was `/Library/Preferences/com.github.waderobson.s3-auth` and the new location is `/Library/Preferences/ManagedInstalls`. This makes sense as the rest of the munki preference keys are stored there too.

**Comment by waderobson** [comment]
Thanks Jared!  As we discussed on slack, changes to where the preferences are stored were recently introduced here #5 
You can work around the problem one of two ways:
- Download an older version `https://raw.githubusercontent.com/waderobson/s3-auth/ef5badf3e22c26f593e4e36ed5ba953546b12f85/middleware_s3.py` or
- Start storing the S3 preferences in `/Library/Preferences/ManagedInstalls` 

Hopefully, this helps anyone else that comes across this.
