### ISSUE TITLE
wiki modification to aws s3 sync command

### ISSUE THREAD

**Issue by sphen13** [waderobson/s3-auth#8]
hey man -

love this - was just walking through a few things and found out the aws s3 sync command is finicky about the exclude.  Please consider changing the following line in your wiki.

From:
```aws s3 sync /path/to/munki/ s3://<S3_BUCKET_GOES_HERE>/ --exclude '*.git/*' --exclude '.DS_Store' --delete```

To:
```aws s3 sync /path/to/munki/ s3://<S3_BUCKET_GOES_HERE>/ --exclude "*.git/*" --exclude "*.DS_Store*" --delete```

Thanks!

**Comment by waderobson** [comment]
Done. Thanks!
